app/main/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
import flask
from flask_login import login_user, logout_user, login_required, current_user
from datetime import date, datetime

import flask_login
from app import bcrypt
from app.models import User, Group, Restaurant
from app.auth.forms import LoginForm, SignUpForm
from app.main.forms import RestaurantForm, GroupForm, JoinGroupForm
# Import Forms

from app import app, db


main = Blueprint('main', __name__)

# :

# Homepage Route
@main.route('/')
def homepage():
    return render_template('base.html')


@main.route('/profile')
def profile():
    groups = current_user.groups
    return render_template('profile.html', groups=groups)

# Create Group
@main.route('/create_group', methods=['GET', 'POST'])
@login_required
def create_group():
    """ This route permits group creation"""
    # IF form is submitted an valid:
    # Create new Group object + save to database,
    # flash sucess message,
    # redirect user to group page
    
    form = GroupForm()

    if form.validate_on_submit():
        new_group = Group(
          created_by = flask_login.current_user,
          name = form.name.data,
          max_atendees = form.max_atendees.data,
          location = form.location.data,
          code = form.code.data,
        )
        current_user.groups.append(new_group)
        db.session.add(new_group)
        db.session.commit()
        flash('Group was created successfully')
        return redirect(url_for('main.profile', group=new_group))
    return render_template('create_group.html', form=form)

# Group Detail

@main.route('/group/<group_id>')
@login_required
def group_details(group_id):
    group = Group.query.get(group_id)
    return render_template('group.html', group=group)

# Join Group

@main.route('/join_group', methods=['GET', 'POST'])
@login_required
def join_group():
    
    form = JoinGroupForm()
    if form.validate_on_submit():
        group = Group.query.filter_by(code=form.code.data).one()
        current_user.groups.append(group)
        print(group.atendees)
        db.session.commit()
        flash('Group was joined successfully')
        return redirect(url_for('main.profile', group=group))
    return render_template('join_group.html', form=form)

# Create Restaurant


@main.route('/create_restaurant/group/<group_id>', methods=['GET', 'POST'])
@login_required
def create_restaurant(group_id):
    print(group_id)
    form = RestaurantForm()

    if form.validate_on_submit():
       new_restaurant = Restaurant(
       name = form.name.data,
       location = form.location.data,
       type = form.type.data,
       price_range = form.price_range.data,
       description = form.description.data,
       created_by=flask_login.current_user,
       photo_url = form.photo_url.data,
       group_id=group_id)
       group_id=group_id
       group = Group.query.filter_by(id=group_id).one()
       group.restaurants.append(new_restaurant)
       db.session.add(new_restaurant)
       db.session.commit()
       flash('Restaurant updated succesfully')
       return redirect(url_for('main.restaurant_detail', restaurant_id=new_restaurant.id))

    
    return render_template('create_restaurant.html', form=form, id=group_id)

#Like Restaurant Route

@main.route('/like_restaurant/<restaurant_id>', methods=['POST'])
@login_required
def like_restaurant(restaurant_id):
    restaurant = Restaurant.query.get(restaurant_id)
    restaurant.liked_by.append(current_user)
    db.session.commit()
    return redirect(url_for('main.restaurant_detail', restaurant_id=restaurant.id))

# Restaurant Details Route

@main.route('/restaurant/<restaurant_id>', methods=['GET', 'POST'])
@login_required
def restaurant_detail(restaurant_id):
    restaurant = Restaurant.query.get(restaurant_id)
    form = RestaurantForm(obj=restaurant)

    if form.validate_on_submit():
       name = form.name.data,
       location = form.location.data,
       type = form.type.data,
       price_range = form.price_range.data,
       description = form.description.data,
       photo_url = form.photo_url.data 
       db.session.add(restaurant)
       db.session.commit()
       flash('Restaurant updated succesfully')
       return redirect(url_for('main.restaurant_detail', restaurant_id=restaurant.id))

    restaurant = Restaurant.query.get(restaurant_id)
    return render_template('restaurant_detail.html', restaurant=restaurant, form=form)

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>Group Eat</title>
    <link rel="stylesheet" href="/static/style.css">
</head>

<body>
    <div id="content">
        {% for message in get_flashed_messages() %}
        <p>{{ message }}</p>
        {% endfor %}
        <nav>
            <a href="/profile">Home</a>
            <div>
                <!-- : Only show these links if the current user is 
                                            authenticated (logged in)! -->
                {% if current_user.is_authenticated %}
                <a href="/logout">Log Out</a>
                <a href="/create_group">Create Group</a>
                <a href="/join_group">Join Group</a>
                {% else %}
                <a href="/signup">Sign Up</a>
                <a href="/login">Log In</a>
                {% endif %}
            </div>
        </nav>

        {% if current_user.is_authenticated %}
        <p>You are logged in as {{ current_user.username }}</p>
        {% endif %}
        
        {% block content %}{% endblock %}
    </div>
</body>

</html>

app/templates/create_group.html
{% extends 'base.html' %}
{% block content %}

<h1>New Group</h1>

<form method="POST" action="{{ url_for('main.create_group')}}">
    {{form.csrf_token}}
    <fieldset>
        <legend>New Group</legend>

        {{form.name.label}}
        {{form.name}}

        {{form.code.label}}
        {{form.code}}

        {{form.max_atendees.label}}
        {{form.max_atendees}}

        {{form.location.label}}
        {{form.location}}

        {{form.submit}}


    </fieldset>
</form>

{% endblock %}

app/templates/create_restaurant.html
{% extends 'base.html' %}
{% block content %}

<h1>New Restaurant</h1>

<form method="POST" action="{{ url_for('main.create_restaurant',group_id=id)}}">
    {{form.csrf_token}}
    <fieldset>
        <legend>New Restaurant</legend>
        
        {{form.name.label}}
        {{form.name}}

        {{form.location.label}}
        {{form.location}}

        {{form.type.label}}
        {{form.type}}

        {{form.price_range.label}}
        {{form.price_range}}

        {{form.description.label}}
        {{form.description}}

        {{form.photo_url.label}}
        {{form.photo_url}}

        {{form.submit}}


    </fieldset>
</form>

{% endblock %}

app/templates/group.html
{% extends 'base.html' %}
{% block content %}

<h1>Name - {{ group.name }}</h1>
<h1>Code - {{ group.code }}</h1>

<strong>Location:</strong> {{ group.location }}

<p><strong>Created By:</strong> {{group.created_by.username}}</p>

<h2>Restaurants</h2>
{% for restaurant in group.restaurants %}
<div class="store">
    <a href="/restaurant/{{ restaurant.id }}"><img src="{{ restaurant.photo_url }}" alt="{{ restaurant.name }}" width="200px">
    <a href="/restaurant/{{ restaurant.id }}"> <br>{{ restaurant.name }}</a>
    
    <p><strong>Location:</strong> {{ restaurant.location }}</p>
    <p><strong>Price Range:</strong> {{ restaurant.price_range }}</p>
    <p><strong>Description:</strong> {{ restaurant.description }}</p>
    <p><strong>Likes:</strong> {{ restaurant.liked_by | length }}</p>
</div>
{% endfor %}
<h2>Atendees:</h2>
<ul>
{% for atendee in group.atendees %}
    <li>{{atendee.name}}</li>
{% endfor %}
</ul>


<form method="POST" action="/create_restaurant/group/{{group.id}}">
    Add New Restaurant
    <br>
    <input type="submit" value="Add">
</form>

{% endblock %}

app/templates/join_group.html
{% extends 'base.html' %}
{% block content %}

<h1>Join Group</h1>

<form method="POST" action="{{ url_for('main.join_group')}}">
    {{form.csrf_token}}
    <fieldset>
        <legend>Join Group</legend>

        {{form.code.label}}
        {{form.code}}
        
        {{form.submit}}

    </fieldset>
</form>

{% endblock %}

app/templates/login.html
{% extends 'base.html' %}
{% block content %}

<h1>Log In</h1>

<form action="/login" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
            {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
            {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

app/templates/profile.html
{% extends 'base.html' %}
{% block content %}


{% for group in groups %}
<div class="restaurants">
    <a href="/group/{{ group.id }}">{{ group.name }}</a> -
    
    <p><strong>Address:</strong> {{ group.location }}</p>
    <br>
    <p><strong>Attendees:</strong> {{ group.atendees | length }}</p>
</div>
{% endfor %}


{% endblock %}

app/templates/restaurant_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Restaurant - {{ restaurant.name }}</h1>

<p><img src="{{ restaurant.photo_url }}" width="250px" height="250px"></p>

<strong>Location:</strong> {{ restaurant.location }}

<h2>Type:</h2> {{ restaurant.type }}

<h2>Price Range:</h2> {{ restaurant.price_range }}

<h3>Description:</h3> {{ restaurant.description }}

<p><strong>Created By:</strong> {{restaurant.created_by.username}}</p>

<h2>Liked By</h2>
<ul>
{% for user in restaurant.liked_by %}
    <li>{{user.name}}</li>
{% endfor %}
</ul>

<form method="POST" action="/like_restaurant/{{restaurant.id}}">
    <label>Like Restaurant</label>
    <input type="submit" value="Submit">
</form>

<h2>Edit Restaurant</h2>

<form method="POST" action="/restaurant/{{restaurant.id}}">
    {{form.csrf_token}}
    <fieldset>
        <legend>New Restaurant</legend>

        {{form.name.label}}
        {{form.name}}

        {{form.location.label}}
        {{form.location}}

        {{form.type.label}}
        {{form.type}}

        {{form.price_range.label}}
        {{form.price_range}}

        {{form.description.label}}
        {{form.description}}

        {{form.photo_url.label}}
        {{form.photo_url}}

        {{form.submit}}


    </fieldset>
</form>



{% endblock %}

app/templates/restaurant_details.html
{% extends 'base.html' %}
{% block content %}

<h1>Restaurant - {{ restaurant.name }}</h1>

<p><img src="{{ restaurant.photo_url }}" width="250px" height="250px"></p>

<strong>Location:</strong> {{ restaurant.location }}

<h2>Type:</h2> {{ restaurant.type }}

<h2>Price Range:</h2> {{ restaurant.price_range }}

<h3>Description:</h3> {{ restaurant.description }}

<p><strong>Created By:</strong> {{restaurant.created_by.username}}</p>

<h2>Liked By</h2>

<div class="restaurants">
    {% for atendee in group.atendees %}
    <div class="restaurant-details">
            <p><strong>{{ atendee.name }}</strong></p>
    </div>
    {% endfor %}
</div>


<h2>Edit Restaurant</h2>

<form method="POST" action="/restaurant/{{restaurant.id}}">
    {{form.csrf_token}}
    <fieldset>
        <legend>New Restaurant</legend>

        {{form.name.label}}
        {{form.name}}

        {{form.location.label}}
        {{form.location}}

        {{form.type.label}}
        {{form.type}}

        {{form.price_range.label}}
        {{form.price_range}}

        {{form.description.label}}
        {{form.description}}

        {{form.photo_url.label}}
        {{form.photo_url}}

        {{form.submit}}


    </fieldset>
</form>

{% endblock %}

app/templates/signup.html
<!-- signup.html -->
{% extends 'base.html' %}
{% block content %}

<h1>Sign Up</h1>

<form action="/signup" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>
        
        {{form.name.label}}
        {{form.name}}
        
        {{ form.username.label }}
        {{ form.username }}
        <ul>
            {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
            {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}